### PR TITLE
Add context menu's commands

### PR DESCRIPTION
**Pull request by gost-serb**
Add possibility to filter files from exploter/editor title context menu
Issue: https://github.com/everettjf/vscode-filter-line/issues/12

### CODE REVIEW

**Comment by everettjf** [comment]
Really thanks

**Comment by gost-serb** [comment]
You are welcome!

**Comment by everettjf** [comment]
https://github.com/microsoft/vscode/issues/9827

**Comment by gost-serb** [comment]
> [microsoft/vscode#9827](https://github.com/microsoft/vscode/issues/9827)

Yeah, I also was thinking about sub-menus. Maybe, as a temporary workaround, QuickPick could be used with all "Filter by..." options.

**Comment by everettjf** [comment]
Hi, New version (1.4.x) has been published. 
Sub-menus could be used when vscode api support sub-menus.
😄

**Pull request merged**
